#!/usr/bin/env ruby

if ARGV.size == 0
  exec "vagrant help"
else
  Dir["*/Vagrantfile"].each do |file|
    box = File.dirname file
    Dir.chdir box do
      puts "==> Running `vagrant #{ARGV.join ' '}` for #{box.inspect}"
      exit 1 unless system "vagrant", *ARGV
    end
  end
end
