# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box      = "ubuntu/trusty64"
  config.vm.hostname = "www.rc"

  config.vm.network "public_network", mac: "0295EAA47613", ip: "172.16.0.4", netmask: "255.255.0.0", bridge: "en0: Ethernet"
  config.vm.network "private_network", type: "dhcp"

  config.vm.synced_folder ".", "/vagrant", :nfs => true

  config.vm.provider "virtualbox" do |vb|
    vb.gui    = false
    vb.memory = "256"
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo "Disabling SSH password auth"
    sudo sed -e 's/PasswordAuthentication\ yes/PasswordAuthentication\ no/' -i /etc/ssh/sshd_config
    sudo service ssh restart

    sudo apt-get update
    sudo apt-get install -y --force-yes nginx
    sudo rm /etc/nginx/sites-available/default
    sudo cp /vagrant/www.rc.conf /etc/nginx/conf.d
  SHELL
end
