# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box      = "ubuntu/trusty64"
  config.vm.hostname = "ntp.rc"

  config.vm.network "public_network", mac: "0211840EDCC7", ip: "172.16.0.2", bridge: "en0: Ethernet"


  config.vm.provider "virtualbox" do |vb|
    vb.gui    = false
    vb.memory = "265"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y --force-yes ntp
  SHELL
end
